name: bloc_event_transformers
description: Configurable transformers for your bloc (bloclibrary.dev) events. Throttle, debounce, skip, and delay with ease.
version: 1.0.1
repository: https://github.com/wrbl-xyz/bloc_event_transformers

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  rxdart: ^0.27.3

dev_dependencies:
  bloc_test: ^9.0.2
  equatable: ^2.0.3
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null

